name: flutter_i18n_plus
description: An advanced internationalization package for Flutter applications with support for plurals, date formatting, and more.
version: 1.0.1
homepage: https://github.com/anse-dev/flutter_i18n_plus

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  assets:
    - test/assets/translations/
